name: 同步 http://hgzspj.51vip.biz/hg1.txt

on:
  schedule:
    # 每天 UTC 时间 0 点执行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 同步文件
        run: |
          import requests
          import os

          # 目标文件 URL
          url = "http://hgzspj.51vip.biz/hg1.txt"
          # 保存路径（根目录下的 hg1.txt）
          save_path = "hg1.txt"

          try:
              # 发送请求获取文件内容
              response = requests.get(url, timeout=30)
              response.raise_for_status()  # 检查请求是否成功

              # 保存文件
              with open(save_path, 'w', encoding='utf-8') as f:
                  f.write(response.text)
              print(f"文件已成功同步至 {save_path}")
          except Exception as e:
              print(f"同步失败: {str(e)}")
              exit(1)
        shell: python {0}

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # 拉取远程最新代码，解决冲突
          git pull --rebase origin main
          # 添加更改的文件
          git add hg1.txt
          # 提交更改，无更改则不提交
          git commit -m "自动同步 http://hgzspj.51vip.biz/hg1.txt $(date +'%Y-%m-%d')" || echo "无更改需提交"
          # 推送更改到远程仓库
          git push
        # 如果你的默认分支是master，请将上面的"origin main"改为"origin master"