name: 同步 http://hgzspj.51vip.biz/hg1.txt

on:
  schedule:
    # 每天 UTC 时间 0 点执行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v4

      - name: 设置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests chardet

      - name: 同步文件
        run: |
          import requests
          import chardet
          from requests.adapters import HTTPAdapter
          from urllib3.util.retry import Retry

          # 目标文件 URL
          url = "http://hgzspj.51vip.biz/hg1.txt"
          save_path = "hg1.txt"

          # 创建带重试机制的session
          session = requests.Session()
          retry_strategy = Retry(
              total=3,
              backoff_factor=0.5,
              status_forcelist=[429, 500, 502, 503, 504],
          )
          adapter = HTTPAdapter(max_retries=retry_strategy)
          session.mount("http://", adapter)
          session.mount("https://", adapter)

          try:
              # 发送请求获取文件内容
              response = session.get(url, timeout=60)
              response.raise_for_status()

              # 自动检测编码
              encoding = chardet.detect(response.content)['encoding'] or 'utf-8'
              content = response.content.decode(encoding)

              # 保存文件
              with open(save_path, 'w', encoding='utf-8') as f:
                  f.write(content)
              print(f"文件已成功同步至 {save_path}")
              
          except Exception as e:
              print(f"同步失败: {str(e)}")
              exit(1)
        shell: python {0}

      - name: 提交更改
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add hg1.txt
          git commit -m "自动同步 http://hgzspj.51vip.biz/hg1.txt $(date +'%Y-%m-%d')" || echo "无更改需提交"
          git push